COMPONENT=shipmainC
CFLAGS += -DRF230_DEF_CHANNEL=20
CFLAGS += -I./SpecialSerialP    #some special serial handling stuff I cooked up
CFLAGS += -I../common      #for types.h and comm.h

TINYOS_ROOT_DIR?=../../tinyos-main
include $(TINYOS_ROOT_DIR)/Makefile.include

